### ISSUE TITLE
hasMagic fails strangely if patterns starts with '#' and nocomments isn't set

### ISSUE THREAD

**Issue by mweststrate** [isaacs/node-glob#152]
The following fails: (expected `false` to be returned, or otherwise an understandable error)

```sh
$ node -e 'require("glob").hasMagic("#")'

/node_modules/glob/glob.js:89
  for (var j = 0; j < set[0].length; j++) {
                            ^
TypeError: Cannot read property 'length' of undefined
    at Function.glob.hasMagic (/node_modules/glob/glob.js:89:29)
    at [eval]:1:17
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
```

Note that with the `nocomments` option this does behave correctly:

```sh
$ node -e 'console.log(require("glob").hasMagic("#",{nocomment:true}))'
false
```

**Comment by isaacs** [comment]
Yeah, I'm going to deprecate comments and negation in the next major release, coming up soon.
