### ISSUE TITLE
Upgrading from 4.0.5 to 5.0.10

### ISSUE THREAD

**Issue by nishant8BITS** [isaacs/node-glob#204]
When upgrading from 4.0.5 to 5.4.10 I get the following error without changing any code. If I go back to 4.0.5 it starts working again. 

```javascript
/Volumes/Nishant/Project/contribute/mean/mean/node_modules/glob/glob.js:69
      throw new TypeError('callback provided to sync glob')
            ^
TypeError: callback provided to sync glob
    at glob (/Volumes/Nishant/Project/contribute/mean/mean/node_modules/glob/glob.js:69:13)
    at module.exports (/Volumes/Nishant/Project/contribute/mean/mean/config/init.js:17:2)
    at Object.<anonymous> (/Volumes/Nishant/Project/contribute/mean/mean/server.js:5:36)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by isaacs** [comment]
You're providing a callback to the sync glob function. That's not allowed. The error message tells you where to fix it in your code.
