### ISSUE TITLE
WIndows 7 directory scanning error 

### ISSUE THREAD

**Issue by askucher** [isaacs/node-glob#216]
``` log
s.js:520
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: EPERM, operation not permitted &apos;D:\&apos;
    at Object.fs.lstatSync (fs.js:520:18)
    at start (fs.js:1017:10)
    at Object.realpathSync (fs.js:1005:3)
    at tryFile (module.js:142:15)
    at Function.Module._findPath (module.js:181:18)
    at Function.Module._resolveFilename (module.js:336:25)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

silent mode doesn't solve the issue.

**Comment by isaacs** [comment]
Can you share the program that's raising this error?  It doesn't look like node-glob is anywhere in that stack trace.

**Comment by isaacs** [comment]
No longer an issue on v9
