### ISSUE TITLE
registory.npmjs.org returns an empty file(glob-5.0.14.tgz)

### ISSUE THREAD

**Issue by kaishuu0123** [isaacs/node-glob#220]
I tried install glob. 
https://registry.npmjs.org/glob/-/glob-5.0.14.tgz return empty file.
(but https://registry.npmjs.org/glob/-/glob-5.0.13.tgz works fine.)

## Console log
```
vagrant@foo:/tmp$ npm install glob
npm ERR! Linux 3.13.0-61-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v0.12.4/bin/node" "/home/vagrant/.nvm/versions/node/v0.12.4/bin/npm" "install" "glob"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! shasum check failed for /tmp/npm-14445-dab7f0ea/registry.npmjs.org/glob/-/glob-5.0.14.tgz
npm ERR! Expected: a811d507acb605441edd6cd2622a3c6f06cc00e1
npm ERR! Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
npm ERR! From:     https://registry.npmjs.org/glob/-/glob-5.0.14.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log

# glob-5.0.14.tgz is Empty
vagrant@foo:/tmp$ file /tmp/npm-14445-dab7f0ea/registry.npmjs.org/glob/-/glob-5.0.14.tgz 
npm-14445-dab7f0ea/registry.npmjs.org/glob/-/glob-5.0.14.tgz: empty
```

## npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vagrant/.nvm/versions/node/v0.12.4/bin/node',
1 verbose cli   '/home/vagrant/.nvm/versions/node/v0.12.4/bin/npm',
1 verbose cli   'install',
1 verbose cli   'glob' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of /tmp/package.json
5 verbose readDependencies loading dependencies from /tmp/package.json
6 silly cache add args [ 'glob', null ]
7 verbose cache add spec glob
8 silly cache add parsed spec { raw: 'glob',
8 silly cache add   scope: null,
8 silly cache add   name: 'glob',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed glob@*
10 verbose addNamed "*" is a valid semver range for glob
11 silly addNameRange { name: 'glob', range: '*', hasData: false }
12 silly mapToRegistry name glob
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/glob
16 verbose addNameRange registry:https://registry.npmjs.org/glob not in flight; fetching
17 verbose request uri https://registry.npmjs.org/glob
18 verbose request no auth needed
19 info attempt registry request try #1 at 21:34:43
20 verbose request id 87ce063a821c4e74
21 verbose etag "EHLVESEWVO4UIHZU5A8323PA9"
22 http request GET https://registry.npmjs.org/glob
23 http 304 https://registry.npmjs.org/glob
24 silly get cb [ 304,
24 silly get   { date: 'Wed, 16 Sep 2015 12:34:40 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"EHLVESEWVO4UIHZU5A8323PA9"',
24 silly get     age: '14',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-nrt6127-NRT',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '2',
24 silly get     'x-timer': 'S1442406880.698961,VS0,VE0',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/glob from cache
26 verbose get saving glob to /home/vagrant/.npm/registry.npmjs.org/glob/.cache.json
27 silly addNameRange number 2 { name: 'glob', range: '*', hasData: true }
28 silly addNameRange versions [ 'glob',
28 silly addNameRange   [ '1.1.0',
28 silly addNameRange     '2.0.9',
28 silly addNameRange     '2.0.8',
28 silly addNameRange     '2.0.7',
28 silly addNameRange     '2.1.0',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '3.0.1',
28 silly addNameRange     '3.1.0',
28 silly addNameRange     '3.1.1',
28 silly addNameRange     '3.1.2',
28 silly addNameRange     '3.1.3',
28 silly addNameRange     '3.1.4',
28 silly addNameRange     '3.1.5',
28 silly addNameRange     '3.1.6',
28 silly addNameRange     '3.1.7',
28 silly addNameRange     '3.1.9',
28 silly addNameRange     '3.1.10',
28 silly addNameRange     '3.1.11',
28 silly addNameRange     '3.1.12',
28 silly addNameRange     '3.1.13',
28 silly addNameRange     '3.1.14',
28 silly addNameRange     '3.1.15',
28 silly addNameRange     '3.1.16',
28 silly addNameRange     '3.1.17',
28 silly addNameRange     '3.1.18',
28 silly addNameRange     '3.1.19',
28 silly addNameRange     '3.1.20',
28 silly addNameRange     '3.1.21',
28 silly addNameRange     '3.2.0',
28 silly addNameRange     '3.2.1',
28 silly addNameRange     '3.2.3',
28 silly addNameRange     '3.2.4',
28 silly addNameRange     '3.2.5',
28 silly addNameRange     '3.2.6',
28 silly addNameRange     '3.2.7',
28 silly addNameRange     '3.2.8',
28 silly addNameRange     '3.2.9',
28 silly addNameRange     '3.2.10',
28 silly addNameRange     '3.2.11',
28 silly addNameRange     '4.0.0',
28 silly addNameRange     '4.0.1',
28 silly addNameRange     '4.0.2',
28 silly addNameRange     '4.0.3',
28 silly addNameRange     '4.0.4',
28 silly addNameRange     '4.0.5',
28 silly addNameRange     '4.0.6',
28 silly addNameRange     '4.1.2-beta',
28 silly addNameRange     '4.1.2',
28 silly addNameRange     '4.1.3',
28 silly addNameRange     '4.1.4',
28 silly addNameRange     '4.1.5',
28 silly addNameRange     '4.1.6',
28 silly addNameRange     '4.2.0',
28 silly addNameRange     '4.2.1',
28 silly addNameRange     '4.2.2',
28 silly addNameRange     '4.3.0',
28 silly addNameRange     '4.3.1',
28 silly addNameRange     '4.3.2',
28 silly addNameRange     '4.3.3',
28 silly addNameRange     '4.3.4',
28 silly addNameRange     '4.3.5',
28 silly addNameRange     '4.4.0',
28 silly addNameRange     '4.4.2',
28 silly addNameRange     '4.5.0',
28 silly addNameRange     '5.0.0',
28 silly addNameRange     '4.5.1',
28 silly addNameRange     '5.0.1',
28 silly addNameRange     '4.5.2',
28 silly addNameRange     '5.0.2',
28 silly addNameRange     '4.5.3',
28 silly addNameRange     '5.0.3',
28 silly addNameRange     '5.0.4',
28 silly addNameRange     '5.0.5',
28 silly addNameRange     '5.0.6',
28 silly addNameRange     '5.0.7',
28 silly addNameRange     '5.0.9',
28 silly addNameRange     '5.0.10',
28 silly addNameRange     '5.0.11',
28 silly addNameRange     '5.0.12',
28 silly addNameRange     '5.0.13',
28 silly addNameRange     '5.0.14' ] ]
29 silly addNamed glob@5.0.14
30 verbose addNamed "5.0.14" is a plain semver version for glob
31 silly mapToRegistry name glob
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/glob
35 verbose addRemoteTarball https://registry.npmjs.org/glob/-/glob-5.0.14.tgz not in flight; adding
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/glob/-/glob-5.0.14.tgz',
36 verbose addRemoteTarball   'a811d507acb605441edd6cd2622a3c6f06cc00e1' ]
37 info retry fetch attempt 1 at 21:34:43
38 info attempt registry request try #1 at 21:34:43
39 http fetch GET https://registry.npmjs.org/glob/-/glob-5.0.14.tgz
40 http fetch 200 https://registry.npmjs.org/glob/-/glob-5.0.14.tgz
41 silly fetchAndShaCheck shasum a811d507acb605441edd6cd2622a3c6f06cc00e1
42 verbose stack Error: shasum check failed for /tmp/npm-14534-86f15aa0/registry.npmjs.org/glob/-/glob-5.0.14.tgz
42 verbose stack Expected: a811d507acb605441edd6cd2622a3c6f06cc00e1
42 verbose stack Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
42 verbose stack From:     https://registry.npmjs.org/glob/-/glob-5.0.14.tgz
42 verbose stack     at /home/vagrant/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/sha/index.js:38:8
42 verbose stack     at ReadStream.<anonymous> (/home/vagrant/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/sha/index.js:85:7)
42 verbose stack     at ReadStream.emit (events.js:129:20)
42 verbose stack     at _stream_readable.js:908:16
42 verbose stack     at process._tickCallback (node.js:355:11)
43 verbose cwd /tmp
44 error Linux 3.13.0-61-generic
45 error argv "/home/vagrant/.nvm/versions/node/v0.12.4/bin/node" "/home/vagrant/.nvm/versions/node/v0.12.4/bin/npm" "install" "glob"
46 error node v0.12.4
47 error npm  v2.10.1
48 error shasum check failed for /tmp/npm-14534-86f15aa0/registry.npmjs.org/glob/-/glob-5.0.14.tgz
48 error Expected: a811d507acb605441edd6cd2622a3c6f06cc00e1
48 error Actual:   da39a3ee5e6b4b0d3255bfef95601890afd80709
48 error From:     https://registry.npmjs.org/glob/-/glob-5.0.14.tgz
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]
```

**Comment by kaishuu0123** [comment]
Probably registry.npmjs.org issue.
but registry all operational.

http://status.npmjs.org/?__hstc=72727564.b3f48442937fad95a45c622742c2078b.1427243672248.1427243672248.1442408107695.2&__hssc=72727564.1.1442408107695&__hsfp=2214759445

**Comment by isaacs** [comment]
I'm seeing files in there:

```
$ npm view glob dist.tarball | xargs curl -s | tar ztv
-rw-r--r--  0 501    20        985 Jul 14 18:34 package/package.json
-rw-r--r--  0 501    20      15445 Jun 18 15:23 package/README.md
-rw-r--r--  0 501    20        765 Jul 28  2014 package/LICENSE
-rw-r--r--  0 501    20       6155 May 21 09:44 package/common.js
-rw-r--r--  0 501    20      18625 Jul 14 18:26 package/glob.js
-rw-r--r--  0 501    20      11461 Jul 14 18:26 package/sync.js
```

Maybe run `npm cache clean` and try again?

**Comment by isaacs** [comment]
Correct shasum, too:

```
$ npm cache clean

$ npm cache add glob

$ npm cache ls
~/.npm
~/.npm/glob/
~/.npm/glob/5.0.14/
~/.npm/glob/5.0.14/package.tgz
~/.npm/glob/5.0.14/package/
~/.npm/glob/5.0.14/package/package.json
~/.npm/registry.npmjs.org/
~/.npm/registry.npmjs.org/glob/
~/.npm/registry.npmjs.org/glob/.cache.json

$ shasum ~/.npm/glob/5.0.14/package.tgz
a811d507acb605441edd6cd2622a3c6f06cc00e1  /Users/isaacs/.npm/glob/5.0.14/package.tgz

$ npm view glob dist.shasum
a811d507acb605441edd6cd2622a3c6f06cc00e1
```

**Comment by kaishuu0123** [comment]
Thank you for your comment.

**Comment by isaacs** [comment]
Aha! Turns out there was a minor operational issue this morning that resulted in a small percentage of zero-byte tarballs being served.  I should probably commit `da39a3ee5e6b4b0d3255bfef95601890afd80709` to memory, because that shasum always indicates a problem ;)

Even though it was a very small percentage, if you were one of the (un)lucky few to get it, it would be cached by the CDN, and keep serving a zero-byte response until our ops folk flushed the caches.  All should be resolved now.
