### ISSUE TITLE
Cannot read property 'length' of undefined at Function.glob.hasMagic

### ISSUE THREAD

**Issue by aristidesfl** [isaacs/node-glob#283]
Any idea why this could be happening?
```
22 08 2016 13:17:07.239:ERROR [karma]: TypeError: Cannot read property 'length' of undefined
  at Function.glob.hasMagic (/Users/user/frontend/node_modules/glob/glob.js:106:29)
  at rimraf (/Users/user/frontend/node_modules/rimraf/rimraf.js:61:36)
  at Object.module.exports.remove (/Users/user/frontend/node_modules/karma/lib/temp_dir.js:28:5)
  at Object._clearTempDirAndReportDone (/Users/user/frontend/node_modules/karma/lib/launchers/process.js:106:13)
  at Object._onProcessExit (/Users/user/frontend/node_modules/karma/lib/launchers/process.js:102:10)
  at ChildProcess.<anonymous> (/Users/user/frontend/node_modules/karma/lib/launchers/process.js:68:12)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by robzolkos** [comment]
@aristidesfl just debugging the same issue.  Only started happening today in CI.

**Comment by aristidesfl** [comment]
- patern is `/var/folders/b_/0n4t_6s17rj85tsxyncd3q6r0000gp/T/karma-69206038`
- object_ is `undefined`

**Comment by robzolkos** [comment]
`var set = g.minimatch.set` is the line that breaks.  

`set` ends up being `[]`

**Comment by eyala-stratoscale** [comment]
@robzolkos @aristidesfl  Seems to be a problem in minimatch itself since this package hasn't been updated in a year

**Comment by mr-beerkiss** [comment]
We're also getting this error in our code.  Stack track is slight different.

As @robzolkos mentions the `set` array is empty.  

```
/my-code/node_modules/rimraf/node_modules/glob/glob.js:110
    for (var j = 0; j < set[0].length; j++) {
                              ^

TypeError: Cannot read property 'length' of undefined
    at Function.glob.hasMagic (/my-code/node_modules/rimraf/node_modules/glob/glob.js:110:31)
    at rimraf (/my-code/node_modules/rimraf/rimraf.js:64:36)
    at ExecBuffer.cleanup (/my-code/node_modules/exec-buffer/index.js:126:2)
    at ExecBuffer.<anonymous> (/my-code/node_modules/exec-buffer/index.js:103:10)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by jeppeolesen** [comment]
@robzolkos Is it Travis CI you're struggling with? I've been trying to figure out a similar bug for a few hours on there, and it just started passing now, without any changes.

**Comment by robzolkos** [comment]
@jeppeolesen mine was Codeship.   So weird.

**Comment by mr-beerkiss** [comment]
We're not running in CI at all and the error is occurring in the local dev environment.  Issue seems limited to *nix though as it is not happening in Windows.

**Comment by robzolkos** [comment]
Yes, mine is failing local dev env too.  I first noticed it failing in CI.

**Comment by vbence86** [comment]
@robzolkos Are you using webpack or imagemin?

**Comment by robzolkos** [comment]
@vbence86 webpack

**Comment by mr-beerkiss** [comment]
Seem to have narrowed it down to a concurrency issue between webpack and imagemin.  When I run them separately they both work but when I try run them in parallel with gulp I get the error.

**Comment by robzolkos** [comment]
Builds are passing in CI now.  Didn't change _anything_.  God bless computers.  Will try locally.

**Comment by phillipj** [comment]
Also stated seeing this as of today, in an inhouse Jenkins setup. Also using webpack, no imagemin involved tho as mentioned above.

**Comment by vbence86** [comment]
The issue magically disappeared after we'd run ```npm install``` again (for the umpteen times).

**Comment by eyala-stratoscale** [comment]
Builds still fail for me. Anyone with any findings ? what about minimatch being updated 12 days ago ?

**Comment by phillipj** [comment]
> Builds still fail for me. Anyone with any findings ? what about minimatch being updated 12 days ago ?

Still failing here as well. Tried to force using the previous minimatch version (3.0.2) by using a shrinkwrap, still fails :(

**Comment by hamishtaplin** [comment]
I'm getting this too in Travis but unable to recreate locally, although my colleague can. Which is pretty weird, frankly.

```[13:14:57] Requiring external module babel-register
[13:14:59] Using gulpfile ~/my_code/gulpfile.babel.js
[13:14:59] Starting 'clean:dist'...
[13:14:59] 'clean:dist' errored after 4.77 ms
[13:14:59] TypeError: Cannot read property 'length' of undefined
   at Function.glob.hasMagic (my_code/node_modules/rimraf/node_modules/glob/glob.js:106:29)
   at Function.rimrafSync [as sync] (my_code/node_modules/rimraf/rimraf.js:272:36)
   at my_code/node_modules/del/index.js:74:10
   at Array.forEach (native)
   at Function.module.exports.sync (my_code/node_modules/del/index.js:67:30)
   at Gulp.<anonymous> (gulpfile.babel.js:40:7)
   at module.exports (my_code/node_modules/orchestrator/lib/runTask.js:34:7)
   at Gulp.Orchestrator._runTask (my_code/node_modules/orchestrator/index.js:273:3)
   at Gulp.Orchestrator._runStep (my_code/node_modules/orchestrator/index.js:214:10)
   at Gulp.Orchestrator.start (my_code/node_modules/orchestrator/index.js:134:8)
   at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
   at nextTickCallbackWith0Args (node.js:452:9)
   at process._tickCallback (node.js:381:13)
   at Function.Module.runMain (module.js:449:11)
   at startup (node.js:139:18)
   at node.js:999:3```

**Comment by vbence86** [comment]
Can you try to devalidate your local npm cache and then run ```npm install``` again?

**Comment by kociolekt** [comment]
Since this [commit](https://github.com/isaacs/node-glob/commit/f0f0872b660d83b1986cd1dd16ec4808fa183adc)
`-    "minimatch": "2 || 3",
+    "minimatch": "^3.0.2",`
maybe version 2.0.10 is working?

**Comment by kociolekt** [comment]
`rm -rf node_modules/
npm cache clean`
worked for me
didn't changed anything else

**Comment by eyala-stratoscale** [comment]
npm cache clean and reinstall worked.
still someone changed something somewhere... pretty terrifying no one is able to find out what.

**Comment by HeLit** [comment]
Had the same issue, resolved itself after the third time running my deployscript in Envoyer. Still clueless why this happened...

Commands run in Envoyer:
cd {{ release }}
npm install
npm run production

Error Message:
/releases/20160822100143/node_modules/glob/glob.js:106
  for (var j = 0; j < set[0].length; j++) {
                            ^
TypeError: Cannot read property 'length' of undefined

**Comment by phillipj** [comment]
As mentioned in https://github.com/sindresorhus/del/issues/58#issuecomment-241606403 it seemed the issue was in math-expression-evaluator, and fixed in https://github.com/redhivesoftware/math-expression-evaluator/pull/2.

In my setup, math-expression-evaluator got installed as a nested dependency of the webpack css-loader. Ensuring v1.2.13 of math-expression-evaluator got installed fixed my builds :fireworks:

**Comment by isaacs** [comment]
This is a result of passing an empty string to hasMagic.

It's fixed in the latest release.

**Comment by isaacs** [comment]
Note: You should probably investigate why you're calling `rimraf('')` though.  That seems like a bug that will result in attempting to recursively delete the current working directory.  Are you *sure* that's what you want to do?
