### ISSUE TITLE
Ignore option breaks possibility to pass whole glob object to next calls

### ISSUE THREAD

**Issue by aczekajski** [isaacs/node-glob#486]
Readme states that
> If you are running many glob operations, you can pass a Glob object as the options argument

and in general it works but breaks when using `ignore`.

Example code:
```js
const { GlobSync } = require('glob');
const g = GlobSync('./*', { ignore: './*.json' });
GlobSync('./*', g);
```
throws
```
Uncaught TypeError: pattern.slice is not a function
    at ignoreMap (...\node_modules\glob\common.js:37:15)
    at Array.map (<anonymous>)
    at setupIgnores (...\node_modules\glob\common.js:30:31)
    at setopts (...\node_modules\glob\common.js:86:3)
    at new GlobSync (...\node_modules\glob\sync.js:37:3)
    at Function.GlobSync (...\node_modules\glob\sync.js:35:12)
```
The same happens with `glob.Glob` (example uses sync version for clarity).

**Comment by isaacs** [comment]
Fixed in v9
