### ISSUE TITLE
glob TypeError: Cannot read properties of null (reading 'withFileTypes')

### ISSUE THREAD

**Issue by djaramil** [isaacs/node-glob#508]
I teach a class in Fullstack web development and some of the sample code uses glob to get a list of files in a directory.  This code has been running fine for over a year with no problem until recently students started to get this crash today and it was working fine last week.   After doing some investigating, I noticed an update in version of glob and with some problem analysis, I've been able to narrow down that the crash occurs with glob version 9.x and works fine with version 8.1.0 and 7.2.3.   

Here is the line of code that is being called:
  glob("students/*.json", null, function (err, files) { 
  .... }

It seems to have an issue with the null parameter.  When I tried something else like in the examples, it would just hang in the glob call.  I tried various options like shown in the readme like:  { withFileTypes: true } but no luck.  Only result was to roll back to the version 8 or 7 of glob.

I though you would want to know of this problem and let me know if you need any more information.

Here is the crash output:
Server is running...
/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/glob/dist/cjs/glob.js:63
        this.withFileTypes = !!opts.withFileTypes;
                                    ^

TypeError: Cannot read properties of null (reading 'withFileTypes')
    at new Glob (/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/glob/dist/cjs/glob.js:63:37)
    at glob (/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/glob/dist/cjs/index.js:20:12)
    at /Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/studentserver.js:80:3
    at Layer.handle [as handle_request] (/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/express/lib/router/layer.js:95:5)
    at /Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/davidjaramillo/Documents/Projects/FAU/FullStack/hw6/hw6---nodejs-api-frontend-giacobn/node_modules/express/lib/router/index.js:280:10)

**Comment by isaacs** [comment]
There were api changes in the [semver](https://semver.org) major bump from v8 to v9. The first version number changing indicates breaking changes that require you to change your code. That is why npm depends on `^X.y.z` by default, which locks the major version.

The changes are summarized in the changelog.md file, and the new api is described in detail in the readme.
